"""
Abstract base class for all platform publishers.
Every platform implements this same 5-method contract, plus one shared
default (attach_media) every platform inherits for free.
The pipeline never changes — adding a platform means
creating one class and adding one line to the registry.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from app.models.media import MediaAsset


@dataclass
class PublishRequest:
    """Everything a publisher needs to post content."""
    piece_id: str
    user_id: str
    brand_id: str
    platform: str
    content: str
    workspace_id: str = ""
    # Real MediaAsset references — replaces the old media_urls: list[str],
    # which existed but was never populated by either real construction
    # site (this file and app/workers/scheduled_posts.py).
    media: list[MediaAsset] = field(default_factory=list)
    platform_user_id: str = ""
    scheduled_at: Optional[datetime] = None
    # YouTube-only — a real, brand-grounded title/description/tags/category/
    # privacy/made-for-kids draft (see app.pipelines.publish.youtube.metadata),
    # generated by POST /api/v1/publish/youtube/prepare and reviewed/edited
    # by the user before the real publish call. When absent (e.g. a
    # programmatic call that skipped the review step), YouTubePublisher
    # generates it fresh from the same function — always real, never a
    # blank/guessed default either way.
    youtube_metadata: Optional[dict] = None


@dataclass
class PublishResult:
    """Standardised result from any platform publisher."""
    success: bool
    platform: str
    piece_id: str
    platform_post_id: Optional[str] = None   # ID of the post on the platform
    platform_post_url: Optional[str] = None  # URL of the published post
    error_type: Optional[str] = None         # TRANSIENT / FIXABLE / AUTH / FATAL
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    retry_after: Optional[int] = None        # seconds to wait before retry
    # Set only by ManualHandoffPublisher — a prefilled compose link for the
    # user to open and click "Post" themselves. success=False whenever this is
    # set: no publish tracking is possible for a manual-handoff platform, so
    # returning success=True would be a lie. Callers that know how to handle
    # a manual action (surface the link, let the user confirm) check this
    # field explicitly rather than treating success=False as a plain failure.
    manual_action_url: Optional[str] = None
    # Set when the piece had media attached but this platform couldn't take
    # it (unsupported format, or the attach step itself failed) — success
    # can still be True (the text half published fine); this is what makes
    # that a visible, honest partial outcome instead of a silent drop. See
    # PlatformPublisher.attach_media below.
    media_dropped_reason: Optional[str] = None


@dataclass
class MediaAttachResult:
    """Outcome of attach_media() — either a usable asset, or an honest
    reason it couldn't be included. Never both, never neither silently."""
    asset: Optional[MediaAsset] = None
    dropped_reason: Optional[str] = None

    @property
    def has_media(self) -> bool:
        return self.asset is not None


class PlatformPublisher(ABC):
    """
    Abstract base class — all platforms implement this contract.
    Five methods. Every publisher, every platform.
    """

    def attach_media(self, request: "PublishRequest") -> MediaAttachResult:
        """Default media-attach decision, inherited by every publisher for
        free — the structural fix for the media_urls/media_dropped bug
        (Facebook/Threads/Bluesky/LinkedIn all silently ignored attached
        media; Instagram only handled a single image).

        Works as-is for any platform whose API fetches media by a plain URL
        server-side (Meta's Graph API family, and by convention most modern
        platform APIs) — the common case, including any of the 64 "planned"
        platforms once they go live, with zero publisher-specific code
        required beyond declaring native_formats in the registry.

        Override this for a platform whose API needs bytes uploaded first
        rather than a bare URL reference (LinkedIn's register-upload flow,
        Bluesky's blob upload).

        Single-asset only in this default — multi-image carousels are a
        per-platform override (Instagram supports them, most don't).

        Consults the platform registry's native_formats — real enforcement
        of what was previously just UI-facing metadata (app.platforms.base
        .PlatformDefinition), so an unsupported media type is a visible,
        honest MediaAttachResult.dropped_reason, never a silent no-op.
        """
        if not request.media:
            return MediaAttachResult()

        from app.platforms.base import import_all, resolve_platform_by_display_value

        import_all()
        # resolve_platform_by_display_value, not get_platform's simple
        # .lower()-keyed lookup — request.platform is the publish
        # subsystem's lowercase slug (app.api.v1.publish.publish_now derives
        # it via display_platform.lower()), which happens to equal every
        # current publisher's registry key by coincidence (linkedin/
        # facebook/threads/bluesky/instagram are all single words). A
        # future platform whose name doesn't collapse that cleanly (a
        # slash, a space) would otherwise silently fail this lookup and
        # have its media wrongly dropped as "unsupported" even when the
        # platform genuinely supports it — the exact mismatch this
        # already-built helper exists to resolve robustly.
        definition = resolve_platform_by_display_value(request.platform)
        asset = request.media[0]

        native = definition.native_formats.get(asset.kind.value) if definition else None
        if native != "native":
            label = definition.label if definition else request.platform
            return MediaAttachResult(
                dropped_reason=f"{label} doesn't support {asset.kind.value} yet"
            )

        return MediaAttachResult(asset=asset)

    @abstractmethod
    def build_auth_url(self, state: str) -> str:
        """
        Return the OAuth URL to redirect the user to.
        State parameter used to prevent CSRF.
        """
        ...

    @abstractmethod
    async def exchange_token(self, code: str) -> dict:
        """
        Exchange OAuth code for access + refresh tokens.
        Returns dict with: access_token, refresh_token, expires_at,
        platform_user_id, username.
        """
        ...

    @abstractmethod
    async def refresh_token(self, refresh_token: str) -> dict:
        """
        Refresh an expiring access token.
        Returns dict with: access_token, expires_at.
        """
        ...

    @abstractmethod
    async def publish(
        self,
        request: PublishRequest,
        access_token: str,
    ) -> PublishResult:
        """
        Post content to the platform.
        Returns PublishResult with success/failure details.
        """
        ...

    @abstractmethod
    def validate_content(self, content: str) -> tuple[bool, list[str]]:
        """
        Validate content against platform rules before publishing.
        Returns (is_valid, list_of_issues).
        Called between generation and publishing.
        """
        ...