from app.platforms.base import PlatformDefinition, register_platform

CATEGORY = "Messaging and community"

ROWS = [
    dict(
        key="telegram", label="Telegram",
        pipelines=frozenset({"text", "image", "video", "audio"}),
        native_formats={"text": "native", "image": "native", "video": "native", "audio": "native"},
        mode="config_driven", integration_pattern="token_webhook",
        rate_limits="Free bot token; no approval needed.",
        policy_constraints=["Channels have no subscriber cap — the only platform here where all four formats post natively."],
        confidence="unverified",
    ),
    dict(
        key="discord", label="Discord",
        pipelines=frozenset({"text", "image", "video", "audio"}),
        native_formats={"text": "native", "image": "attachment", "video": "attachment", "audio": "attachment"},
        mode="config_driven", integration_pattern="token_webhook",
        rate_limits="Free webhook.",
        policy_constraints=["Community-first; webhooks post without OAuth."],
        confidence="unverified",
    ),
    dict(
        key="slack", label="Slack",
        pipelines=frozenset({"text", "image", "video", "audio"}),
        native_formats={"text": "native", "image": "attachment", "video": "attachment", "audio": "attachment"},
        mode="config_driven", integration_pattern="token_webhook",
        rate_limits="Free webhook (verify current plan limits).",
        policy_constraints=["Internal audience — shares published content with the team, not a public post."],
        confidence="unverified",
    ),
    dict(
        key="microsoft_teams", label="Microsoft Teams",
        pipelines=frozenset({"text"}),
        native_formats={"text": "card"},
        mode="config_driven", integration_pattern="token_webhook",
        rate_limits="Free webhook (verify current method — Teams has changed its webhook mechanism before).",
        policy_constraints=["Enterprise audience; workflow-based incoming webhooks."],
        confidence="unverified",
    ),
    dict(
        key="google_chat", label="Google Chat",
        pipelines=frozenset({"text"}),
        native_formats={"text": "native"},
        mode="config_driven", integration_pattern="token_webhook",
        rate_limits="Free webhook.",
        policy_constraints=["Google Workspace teams; same role as Slack for Google-native orgs."],
        confidence="unverified",
    ),
    dict(
        key="whatsapp_channels", label="WhatsApp Channels",
        pipelines=frozenset({"text", "image", "video", "audio"}),
        native_formats={"text": "manual", "image": "manual", "video": "manual", "audio": "manual"},
        mode="config_driven", integration_pattern="manual_handoff",
        policy_constraints=["Huge reach in India, Brazil and Indonesia; no publishing API exists."],
        access_notes="Manual only — ready-to-paste formatted posts.",
        confidence="unverified",
    ),
    dict(
        key="whatsapp_business", label="WhatsApp Business",
        pipelines=frozenset({"text", "image", "video", "audio"}),
        native_formats={"text": "native", "image": "native", "video": "native", "audio": "native"},
        mode="code_driven", integration_pattern="api_publish",
        audit_required=True,
        rate_limits="Approval and per-message fees apply (verify current pricing).",
        policy_constraints=["Opt-in required; message templates need approval before they can be sent."],
        confidence="unverified",
    ),
    dict(
        key="line", label="LINE",
        pipelines=frozenset({"text", "image", "video", "audio"}),
        native_formats={"text": "native", "image": "native", "video": "native", "audio": "native"},
        mode="code_driven", integration_pattern="api_publish",
        rate_limits="Messaging API; plan limits apply (verify).",
        policy_constraints=["Leading messenger in Japan, Thailand, Taiwan — Official Accounts broadcast to followers."],
        confidence="unverified",
    ),
    dict(
        key="kakaotalk", label="KakaoTalk",
        pipelines=frozenset({"text", "image"}),
        native_formats={"text": "native", "image": "native"},
        mode="code_driven", integration_pattern="api_publish",
        audit_required=True,
        rate_limits="Business channel approval required (verify).",
        policy_constraints=["Korea's main messenger; a business Channel is required to publish."],
        confidence="unverified",
    ),
    dict(
        key="discourse", label="Discourse",
        pipelines=frozenset({"text", "image"}),
        native_formats={"text": "native", "image": "native"},
        mode="code_driven", integration_pattern="api_publish",
        rate_limits="Free API — each Discourse site issues its own API key (verify).",
        policy_constraints=["Long threaded discussion forum software, self-hosted per community."],
        confidence="unverified",
    ),
    dict(
        key="circle", label="Circle",
        pipelines=frozenset({"text", "image", "video"}),
        native_formats={"text": "native", "image": "native", "video": "native"},
        mode="code_driven", integration_pattern="api_publish",
        rate_limits="API available on paid plans only (verify).",
        policy_constraints=["Paid creator-community platform — posts land in member spaces, not a public feed."],
        confidence="unverified",
    ),
]

for _row in ROWS:
    register_platform(PlatformDefinition(category=CATEGORY, status="planned", **_row))
